// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBPG3yaMtVIJNGZnH7TUZRE-rvnVQ9_P8',
    appId: '1:306414832647:web:6faae22bb7aaf2056ceea2',
    messagingSenderId: '306414832647',
    projectId: 'coffee-review-app-pt2',
    authDomain: 'coffee-review-app-pt2.firebaseapp.com',
    storageBucket: 'coffee-review-app-pt2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjCZzplXyqJtLtNKvIu6p6NalfYANgUWY',
    appId: '1:306414832647:android:52ac70170d66b8386ceea2',
    messagingSenderId: '306414832647',
    projectId: 'coffee-review-app-pt2',
    storageBucket: 'coffee-review-app-pt2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI7OpEs08GA-9DNjqpA16Yb5mZD5RLAio',
    appId: '1:306414832647:ios:2bafa24401ad6a336ceea2',
    messagingSenderId: '306414832647',
    projectId: 'coffee-review-app-pt2',
    storageBucket: 'coffee-review-app-pt2.firebasestorage.app',
    iosBundleId: 'com.example.coffeeReviewAppPt2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI7OpEs08GA-9DNjqpA16Yb5mZD5RLAio',
    appId: '1:306414832647:ios:2bafa24401ad6a336ceea2',
    messagingSenderId: '306414832647',
    projectId: 'coffee-review-app-pt2',
    storageBucket: 'coffee-review-app-pt2.firebasestorage.app',
    iosBundleId: 'com.example.coffeeReviewAppPt2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBPG3yaMtVIJNGZnH7TUZRE-rvnVQ9_P8',
    appId: '1:306414832647:web:44b0b243ce66433b6ceea2',
    messagingSenderId: '306414832647',
    projectId: 'coffee-review-app-pt2',
    authDomain: 'coffee-review-app-pt2.firebaseapp.com',
    storageBucket: 'coffee-review-app-pt2.firebasestorage.app',
  );

}