name: coffee_review_app_pt2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: any
  google_maps_flutter: any
  geolocator: any
  flutter_rating_bar: any
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
